/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.gestioncourses.views.responsableEquipe;

import com.mycompany.gestioncourses.models.Coureur;
import com.mycompany.gestioncourses.models.Edition;
import com.mycompany.gestioncourses.models.Equipe;
import com.mycompany.gestioncourses.models.ParticipationEquipe;
import com.mycompany.gestioncourses.services.CoureurService;
import com.mycompany.gestioncourses.services.ParticipationEquipeService;
import com.mycompany.gestioncourses.services.ParticipationService;
import com.mycompany.gestioncourses.views.MainFrame;
import com.mycompany.gestioncourses.views.utils.DropDownRenderer;
import io.ebean.annotation.Transactional;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import static java.util.stream.Collectors.toList;
import javax.swing.JComboBox;

/**
 *
 * @author David_C
 */
public class ComposerEquipePanel extends javax.swing.JPanel implements ActionListener {

    private MainFrame frame;
    private final CoureurService coureurService = CoureurService.getInstance();
    private final ParticipationEquipeService participationEquipeService = ParticipationEquipeService.getInstance();
    private final ParticipationService participationService = ParticipationService.getInstance();
    private final List<Coureur> coureurs;
    private final Equipe equipe;
    private final Edition edition;
    private final List<JComboBox<Coureur>> choixCoureurs;
    /**
     * Creates new form ConnexionEquipePanel
     */
    public ComposerEquipePanel(MainFrame frame, Equipe equipe, Edition editionSelectionnee) {
        this.frame = frame;
        this.equipe = equipe;
        this.edition = editionSelectionnee;
        this.coureurs = coureurService.coureurSansEquipe(editionSelectionnee);
        initComponents();
        
        this.choixCoureurs = new ArrayList<>();
        this.choixCoureurs.add(this.coureur1);
        this.choixCoureurs.add(this.coureur2);
        this.choixCoureurs.add(this.coureur3);
        this.choixCoureurs.add(this.coureur4);
        this.choixCoureurs.add(this.coureur5);
        this.choixCoureurs.add(this.coureur6);
        this.choixCoureurs.add(this.coureur7);
        this.choixCoureurs.add(this.coureur8);
        this.choixCoureurs.add(this.coureur9);
        this.choixCoureurs.add(this.coureur10);
        
        this.choixCoureurs.forEach(choix -> {
            choix.setRenderer(new DropDownRenderer<>(Coureur::getNom));
            choix.addActionListener(this);
            this.coureurs.forEach(coureur -> choix.addItem(coureur));
        });
    }

    @Override
    public void actionPerformed(ActionEvent e) {
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        coureur1 = new javax.swing.JComboBox<>();
        boutonInscription = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        coureur2 = new javax.swing.JComboBox<>();
        coureur3 = new javax.swing.JComboBox<>();
        coureur4 = new javax.swing.JComboBox<>();
        coureur5 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        coureur6 = new javax.swing.JComboBox<>();
        coureur7 = new javax.swing.JComboBox<>();
        coureur8 = new javax.swing.JComboBox<>();
        coureur9 = new javax.swing.JComboBox<>();
        coureur10 = new javax.swing.JComboBox<>();
        labelErreur = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        jLabel6.setText("jLabel6");

        jTextField1.setText("jTextField1");

        jTextField2.setText("jTextField2");

        coureur1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coureur1ActionPerformed(evt);
            }
        });

        boutonInscription.setText("Inscrire");
        boutonInscription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonInscriptionActionPerformed(evt);
            }
        });

        jLabel1.setText("Coureur 1 :");

        jLabel2.setText("Coureur 2 : ");

        jLabel3.setText("Coureur 3 :");

        jLabel4.setText("Coureur 4 :");

        jLabel5.setText("Coureur 5 :");

        jLabel7.setText("Inscription des coureurs de l'équipe");

        jLabel8.setText("Coureur 6 :");

        jLabel9.setText("Coureur 7 : ");

        jLabel10.setText("Coureur 8 :");

        jLabel11.setText("Coureur 9 :");

        jLabel12.setText("Coureur 10 :");

        jLabel13.setText("jLabel13");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(coureur2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(coureur4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel13)
                                .addComponent(jLabel5))
                            .addGap(18, 18, 18)
                            .addComponent(coureur5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(21, 21, 21)
                        .addComponent(coureur1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(21, 21, 21)
                        .addComponent(coureur3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 206, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(coureur7, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(coureur6, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(coureur10, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(coureur9, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(coureur8, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(55, 55, 55))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(231, 231, 231))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(boutonInscription)
                        .addGap(289, 289, 289))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelErreur)
                        .addGap(303, 303, 303))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(coureur1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(coureur6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(coureur2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(coureur7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(coureur3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(coureur8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(coureur4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(coureur9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(coureur5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(coureur10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelErreur)
                .addGap(33, 33, 33)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(boutonInscription)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void coureur1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coureur1ActionPerformed
        
    }//GEN-LAST:event_coureur1ActionPerformed

    @Transactional
    private void boutonInscriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonInscriptionActionPerformed
        final List<Coureur> coureurChoisis = this.choixCoureurs.stream()
                .map(selecteur -> (Coureur) selecteur.getSelectedItem())
                .collect(toList());
        
        if (coureurChoisis.stream().anyMatch(c -> c == null)) {
            labelErreur.setText("Veuillez sélectionner les 10 coureurs");
            return;
        }
        
        Set<Integer> ids = new HashSet<>(coureurChoisis.stream().map(Coureur::getId).collect(toList()));
        if (ids.size() < 10) {
            labelErreur.setText("Veuillez sélectionner des coureurs distincts");
            return;
        }
        
        ParticipationEquipe pEquipe = this.participationEquipeService.creerParticipationEquipe(this.equipe, this.edition);
        for (Coureur coureur: coureurChoisis) {
            this.participationService.creerParticipation(pEquipe, coureur, this.equipe);
        }
        
        this.frame.displayConsultationInscriptionsEquipePanel(this.equipe);
    }//GEN-LAST:event_boutonInscriptionActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boutonInscription;
    private javax.swing.JComboBox<Coureur> coureur1;
    private javax.swing.JComboBox<Coureur> coureur10;
    private javax.swing.JComboBox<Coureur> coureur2;
    private javax.swing.JComboBox<Coureur> coureur3;
    private javax.swing.JComboBox<Coureur> coureur4;
    private javax.swing.JComboBox<Coureur> coureur5;
    private javax.swing.JComboBox<Coureur> coureur6;
    private javax.swing.JComboBox<Coureur> coureur7;
    private javax.swing.JComboBox<Coureur> coureur8;
    private javax.swing.JComboBox<Coureur> coureur9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel labelErreur;
    // End of variables declaration//GEN-END:variables
}
