/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.gestioncourses.views.responsableEquipe;

import com.mycompany.gestioncourses.views.MainFrame;

/**
 *
 * @author ams
 */
public class MenuResponsableEquipePanel extends javax.swing.JPanel {

    private MainFrame frame; 
    /**
     * Creates new form MenuResponsableEquipePanel
     * @param frame
     */
    public MenuResponsableEquipePanel(MainFrame frame) {
        this.frame = frame; 
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        utilisateur = new javax.swing.JButton();
        consultationEditionResponsable = new javax.swing.JButton();
        consultationInscriptionResponsable = new javax.swing.JButton();

        utilisateur.setText("Choix utilisateur");
        utilisateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                utilisateurActionPerformed(evt);
            }
        });

        consultationEditionResponsable.setText("Consultation d'édition ");
        consultationEditionResponsable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultationEditionResponsableActionPerformed(evt);
            }
        });

        consultationInscriptionResponsable.setText("Consultation des inscriptions");
        consultationInscriptionResponsable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultationInscriptionResponsableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(utilisateur)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(consultationEditionResponsable)
                .addGap(77, 77, 77)
                .addComponent(consultationInscriptionResponsable)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(utilisateur)
                .addGap(117, 117, 117)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consultationEditionResponsable)
                    .addComponent(consultationInscriptionResponsable))
                .addContainerGap(131, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void consultationEditionResponsableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultationEditionResponsableActionPerformed
        this.frame.displayConsultationEditionResponsablePanel();
    }//GEN-LAST:event_consultationEditionResponsableActionPerformed

    private void utilisateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_utilisateurActionPerformed
        this.frame.displayUtilisateur();
    }//GEN-LAST:event_utilisateurActionPerformed

    private void consultationInscriptionResponsableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultationInscriptionResponsableActionPerformed
        this.frame.displayConsultationInscriptionResponsablePanel();
    }//GEN-LAST:event_consultationInscriptionResponsableActionPerformed
                                         
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton consultationEditionResponsable;
    private javax.swing.JButton consultationInscriptionResponsable;
    private javax.swing.JButton utilisateur;
    // End of variables declaration//GEN-END:variables
}
