/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.gestioncourses.views.responsableEquipe;

import com.mycompany.gestioncourses.models.Equipe;
import com.mycompany.gestioncourses.views.MainFrame;

/**
 *
 * @author David_C
 */
public class MenuResponsablePanel extends javax.swing.JPanel {

    /**
     * Creates new form MenuResponsablePanel
     */
   private MainFrame frame;
   private Equipe equipe;
    /**
     * Creates new form InscriptionEquipePanel
     */

    public MenuResponsablePanel(MainFrame frame, Equipe equipe) {
        this.frame = frame;
        this.equipe = equipe;
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        consultationEd = new javax.swing.JButton();
        consultationInscrip = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(400, 368));

        consultationEd.setFont(new java.awt.Font("Maiandra GD", 0, 12)); // NOI18N
        consultationEd.setText("Consultation d'édition");
        consultationEd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultationEditActionPerformed(evt);
            }
        });

        consultationInscrip.setFont(new java.awt.Font("Maiandra GD", 0, 12)); // NOI18N
        consultationInscrip.setText("Consultation des inscriptions");
        consultationInscrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultationInscripActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(153, 204, 255));
        jButton3.setText("Choix utilisateur");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                utilisateurActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(consultationEd, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(consultationInscrip, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3)
                .addGap(145, 145, 145)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consultationEd, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(consultationInscrip, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(149, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ConsultationEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultationEditActionPerformed
        this.frame.displayConsultationEditionsEquipePanel(this.equipe);
    }//GEN-LAST:event_ConsultationEditActionPerformed

    private void utilisateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_utilisateurActionPerformed
        this.frame.displayUtilisateur();
    }//GEN-LAST:event_utilisateurActionPerformed

    private void consultationInscripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultationInscripActionPerformed
        this.frame.displayConsultationInscriptionsEquipePanel(this.equipe);
    }//GEN-LAST:event_consultationInscripActionPerformed
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton consultationEd;
    private javax.swing.JButton consultationInscrip;
    private javax.swing.JButton jButton3;
    // End of variables declaration//GEN-END:variables
}
