ebean:
  ddl:
    platform: sqlite
    generate: true
    dbName: course
    dllMode: migrations
    # run: true
    
datasource:
  db:
    username: a
    password: a
    url: jdbc:sqlite:.database-db