ebean:
  ddl:
    platform: sqlite
    generate: true
    dbName: course
    dllMode: create
    # run: true
    
datasource:
  db:
    username: a
    password: a
    url: jdbc:sqlite:.database-db
    driver-class-name: org.sqlite.JDBC
  databaseDriver: org.sqlite.JDBC
