/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package membreFFC;

import com.mycompany.gestioncourses.views.MainFrame;

/**
 *
 * @author ams
 */
public class MenuMembrePanel extends javax.swing.JPanel {
    
    private MainFrame frame; 

    /**
     * Creates new form MenuMembrePanel
     */
    public MenuMembrePanel(MainFrame frame) {
        this.frame = frame; 
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        accueilMembre = new javax.swing.JLabel();
        consultationEditionMembre = new javax.swing.JButton();
        consultationClassementMembre = new javax.swing.JButton();
        utilisateur = new javax.swing.JButton();

        accueilMembre.setText("Accueil Membre FFC ");

        consultationEditionMembre.setText("Consultation Edition");
        consultationEditionMembre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultationEditionMembreActionPerformed(evt);
            }
        });

        consultationClassementMembre.setText("Consultation Classement ");
        consultationClassementMembre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultationClassementMembreActionPerformed(evt);
            }
        });

        utilisateur.setText("Choix utilisateur");
        utilisateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                utilisateurActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(consultationEditionMembre)
                        .addGap(42, 42, 42)
                        .addComponent(consultationClassementMembre)
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(accueilMembre)
                        .addGap(190, 190, 190))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(utilisateur)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(utilisateur)
                .addGap(12, 12, 12)
                .addComponent(accueilMembre)
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consultationEditionMembre)
                    .addComponent(consultationClassementMembre))
                .addContainerGap(135, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void consultationEditionMembreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultationEditionMembreActionPerformed
        this.frame.displayConsultationEditionMembrePanel();
    }//GEN-LAST:event_consultationEditionMembreActionPerformed

    private void consultationClassementMembreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultationClassementMembreActionPerformed
        this.frame.displayConsultationClassementMembrePanel();
    }//GEN-LAST:event_consultationClassementMembreActionPerformed

    private void utilisateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_utilisateurActionPerformed
        this.frame.displayUtilisateur();
    }//GEN-LAST:event_utilisateurActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accueilMembre;
    private javax.swing.JButton consultationClassementMembre;
    private javax.swing.JButton consultationEditionMembre;
    private javax.swing.JButton utilisateur;
    // End of variables declaration//GEN-END:variables
}
