/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.gestioncourses.views;

/**
 *
 * @author Emilie
 */
public class MenuOrganisateurPanel extends javax.swing.JPanel {

    private MainFrame frame;
    /**
     * Creates new form CreationCoursePanel
     */
    public MenuOrganisateurPanel(MainFrame frame) {
        this.frame = frame;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        creationCourse = new javax.swing.JButton();
        creationEdition = new javax.swing.JButton();
        ConsulterEdition = new javax.swing.JButton();
        consulterClassement = new javax.swing.JButton();
        utilisateur = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Accueil Organisateur");

        creationCourse.setText("Création d'une course");
        creationCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creationCourseActionPerformed(evt);
            }
        });

        creationEdition.setText("Creation édition");
        creationEdition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creationEditionActionPerformed(evt);
            }
        });

        ConsulterEdition.setText("Consulter édition");

        consulterClassement.setText("Consultation classement");

        utilisateur.setText("Choix Utilisateur");
        utilisateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                utilisateurActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(utilisateur)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(32, 32, 32)
                            .addComponent(creationCourse)
                            .addGap(40, 40, 40)
                            .addComponent(creationEdition)
                            .addGap(38, 38, 38)
                            .addComponent(ConsulterEdition)
                            .addGap(44, 44, 44)
                            .addComponent(consulterClassement))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(330, 330, 330)
                            .addComponent(jLabel1))))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(utilisateur)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creationCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(creationEdition)
                    .addComponent(ConsulterEdition)
                    .addComponent(consulterClassement))
                .addContainerGap(123, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void creationCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creationCourseActionPerformed
        frame.displayCreationCoursePanel();
    }//GEN-LAST:event_creationCourseActionPerformed

    private void creationEditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creationEditionActionPerformed
        frame.displayCreationEditionPanel();
    }//GEN-LAST:event_creationEditionActionPerformed

    private void utilisateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_utilisateurActionPerformed
        frame.displayUtilisateur();
    }//GEN-LAST:event_utilisateurActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConsulterEdition;
    private javax.swing.JButton consulterClassement;
    private javax.swing.JButton creationCourse;
    private javax.swing.JButton creationEdition;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton utilisateur;
    // End of variables declaration//GEN-END:variables
}
