/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.gestioncourses.views;

/**
 *
 * @author Emilie
 */
public class UtilisateurPanel extends javax.swing.JPanel {

    private MainFrame frame;
    /**
     * Creates new form CreationCoursePanel
     */
    public UtilisateurPanel(MainFrame frame) {
        this.frame = frame;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        organisateur = new javax.swing.JButton();
        coureur = new javax.swing.JButton();
        responsableEquipe = new javax.swing.JButton();
        jury = new javax.swing.JButton();
        membreFFC = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jLabel1.setText("Tableau de bord ");

        organisateur.setBackground(new java.awt.Color(204, 204, 204));
        organisateur.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 14)); // NOI18N
        organisateur.setText("Organisateur");
        organisateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organisateurActionPerformed(evt);
            }
        });

        coureur.setBackground(new java.awt.Color(204, 204, 204));
        coureur.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 14)); // NOI18N
        coureur.setText("Coureur");
        coureur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coureurActionPerformed(evt);
            }
        });

        responsableEquipe.setBackground(new java.awt.Color(204, 204, 204));
        responsableEquipe.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 14)); // NOI18N
        responsableEquipe.setText("Responsable d'équipe");
        responsableEquipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                responsableEquipeActionPerformed(evt);
            }
        });

        jury.setBackground(new java.awt.Color(204, 204, 204));
        jury.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 14)); // NOI18N
        jury.setText("Jury");
        jury.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                juryActionPerformed(evt);
            }
        });

        membreFFC.setBackground(new java.awt.Color(204, 204, 204));
        membreFFC.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 14)); // NOI18N
        membreFFC.setText("Membre FFC");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(organisateur)
                .addGap(46, 46, 46)
                .addComponent(coureur)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(186, 186, 186))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(responsableEquipe)
                        .addGap(42, 42, 42)
                        .addComponent(jury)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(membreFFC)
                        .addGap(35, 35, 35))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(organisateur, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coureur, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(responsableEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jury, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(membreFFC, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(135, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void organisateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organisateurActionPerformed
        frame.displayMenuOrganisateur();
    }//GEN-LAST:event_organisateurActionPerformed

    private void coureurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coureurActionPerformed
        this.frame.displayConnexionCoureurPanel();
    }//GEN-LAST:event_coureurActionPerformed

    private void juryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_juryActionPerformed
        this.frame.displayMenuJuryPanel();
    }//GEN-LAST:event_juryActionPerformed

    private void responsableEquipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_responsableEquipeActionPerformed
        this.frame.displayConnexionEquipePanel();
    }//GEN-LAST:event_responsableEquipeActionPerformed

     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton coureur;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jury;
    private javax.swing.JButton membreFFC;
    private javax.swing.JButton organisateur;
    private javax.swing.JButton responsableEquipe;
    // End of variables declaration//GEN-END:variables
}
