/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.gestioncourses.views;

/**
 *
 * @author Emilie
 */
public class UtilisateurPanel extends javax.swing.JPanel {

    private MainFrame frame;
    /**
     * Creates new form CreationCoursePanel
     */
    public UtilisateurPanel(MainFrame frame) {
        this.frame = frame;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        organisateur = new javax.swing.JButton();
        coureur = new javax.swing.JButton();
        responsableEquipe = new javax.swing.JButton();
        jury = new javax.swing.JButton();
        membreFFC = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Choix utilisateur");

        organisateur.setText("Organisateur");
        organisateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organisateurActionPerformed(evt);
            }
        });

        coureur.setText("Coureur");
        coureur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coureurActionPerformed(evt);
            }
        });

        responsableEquipe.setText("Responsable d'équipe");

        jury.setText("Jury");
        jury.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                juryActionPerformed(evt);
            }
        });

        membreFFC.setText("Membre FFC");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(organisateur)
                        .addGap(40, 40, 40)
                        .addComponent(coureur)
                        .addGap(38, 38, 38)
                        .addComponent(responsableEquipe)
                        .addGap(44, 44, 44)
                        .addComponent(jury)
                        .addGap(27, 27, 27)
                        .addComponent(membreFFC))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(345, 345, 345)
                        .addComponent(jLabel1)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel1)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(organisateur)
                    .addComponent(coureur)
                    .addComponent(responsableEquipe)
                    .addComponent(jury)
                    .addComponent(membreFFC))
                .addContainerGap(123, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void organisateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organisateurActionPerformed
        frame.displayMenuOrganisateur();
    }//GEN-LAST:event_organisateurActionPerformed

    private void coureurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coureurActionPerformed
        this.frame.displayInscriptionCoureurPanel();
    }//GEN-LAST:event_coureurActionPerformed

    private void juryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_juryActionPerformed
        this.frame.displayMenuJuryPanel();
    }//GEN-LAST:event_juryActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton coureur;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jury;
    private javax.swing.JButton membreFFC;
    private javax.swing.JButton organisateur;
    private javax.swing.JButton responsableEquipe;
    // End of variables declaration//GEN-END:variables
}
